steps:
  - id: 'Test, Build and Publish the app'
    name: 'maven:3.8.3-jdk-11'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        mvn -nsu -B --no-transfer-progress install deploy
timeout: 1800s
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-east4/workerPools/dmv-private-pool'
