steps:
  - id: 'GitHub and CloudBuild Authentication'
    name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY', 'PUBLIC_SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        echo "$$PUBLIC_SSH_KEY" >> /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - id: 'Test and Build the app'
    name: 'maven:3.8.3-jdk-11'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        git config --global user.email "NY-GCP-bot"
        git config user.email ctavares@nuvalence.io
        mvn -nsu -B --no-transfer-progress install -DskipTests release:prepare release:perform -X
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  # - id: 'Publish snapshots'
  #   name: 'maven:3.8.3-jdk-11'
  #   entrypoint: /bin/bash
  #   args:
  #     - '-c'
  #     - |
  #       mvn -B deploy
  # - id: 'Prepare and publish release'
  #   name: 'gcr.io/cloud-builders/mvn'
  #   entrypoint: /bin/bash
  #   args:
  #     - '-c'
  #     - |
  #       git config --global user.email "NY-GCP-bot"
  #       git config user.email ctavares@nuvalence.io
  #       mvn -B release:prepare release:perform
  #   volumes:
  #     - name: 'ssh'
  #       path: /root/.ssh
timeout: 1800s
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-key-bot/versions/latest
    env: 'SSH_KEY'
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-key-public-bot/versions/latest
    env: 'PUBLIC_SSH_KEY'
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-east4/workerPools/dmv-private-pool'
